# Generated by Django 4.0.3 on 2022-04-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0005_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='рейтинг'),
        ),
    ]
