# Generated by Django 4.0.3 on 2022-04-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0006_product_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
