# Generated by Django 4.0.3 on 2022-04-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0007_alter_profile_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
