# Generated by Django 4.0.3 on 2022-04-11 10:53
import random
from django.db import migrations


def make_prods(apps, schema_editor):
    NUM_PRODS = 100
    MARKETS = ('Каджит', 'Яндекс', 'Ali')
    FIRST_WORD = ('strange', 'good', 'weird', 'best')
    SECOND_WORD = ('phone', 'sword', 'book', 'wine')
    Product = apps.get_model('app_goods', 'Product')

    for _ in range(NUM_PRODS):
        Product.objects.create(title=random.choice(FIRST_WORD) +
                                     ' ' + random.choice(SECOND_WORD),
                               market=random.choice(MARKETS),
                               description='lorem ipsum',
                               price=random.randint(100, 2000),
                               rate=0)


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(make_prods)
    ]
