# Generated by Django 4.0.3 on 2022-04-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0008_remove_profile_first_name_remove_profile_last_name'),
        ('app_goods', '0009_auto_20220411_1353'),
    ]

    operations = [
    ]
